### PR TITLE
Update the documents and code base

### PR DESCRIPTION
**Pull request by GreatenAnoymous**
1. updated the markdown document
2.  removed unused Python scripts
3. merged benchmark generators

### CODE REVIEW

**Comment by nobodyczcz** [comment]
Related issue: https://github.com/MAPF-Competition/Benchmark-Archive/issues/1

**Comment by nobodyczcz** [comment]
Hi Teng @GreatenAnoymous, I found some bugs when running the following example command in the tutorial.md

For example usage on benchmark_generator with random tasks
```shell
python3 ./script/benchmark_generator.py  --mapFile  /random.domain/maps/random-32-32-20.map  --problemName randomTest --taskNum 5 --team_sizes 100 200 300 --benchmark_folder ./test 
```

1. ModuleNotFoundError: No module named 'task_generator'

Traceback (most recent call last):
  File "./script/benchmark_generator.py", line 1, in <module>
    from task_generator import WarehouseTaskGenerator
ModuleNotFoundError: No module named 'task_generator'

2. dependent on 'easydict' package

easydict is not a built-in Python package. We should add a dependency section to clarify this dependency.

3. benchmark_generator.py: error: unrecognized arguments: --team_sizes 100 200 300

Should be --teamSizes

5. AttributeError: 'RandomBenchmarkGenerator' object has no attribute 'create_benchmark_folders'

For example usage on the warehouse map generator
```shell
python ./script/warehouse_generator.py --config ./script/sortation_medium.yaml
```
1.  warehouse_generator.py 

warehouse_generator.py was renamed to warehouse_map_generator.py already.

2. if using ./script/warehouse_map_generator.py, will get FileNotFoundError: [Errno 2] No such file or directory: '~~~~~ Problem Generator/script/./script/sortation_medium.yaml' 

the script is looking for files relative to the location of warehouse_map_generator.py, thus it cannot find  ./script/sortation_medium.yaml

3. should clarify that the code produces the map under the folder where warehouse_map_generator.py lives, not the current working folder.

4. similar issues to other example usage on warehouse_map_generator

For example usage on the warehouse task generator
```shell
 python3 ./script/warehouse_task_generator.py --mapFile /warehouse.domain/maps/warehouse_large.map  --taskNum 100 --taskFile ./tasks.tasks --m_buckets 5
```
1. /warehouse.domain/maps/warehouse_large.map  no longer exists here

Better switch to a map file generated from earlier examples.

For example usage on benchmark generator with a give task file
```shell
python3 ./script/benchmark_generator.py  --mapFile /warehouse.domain/maps/warehouse_large.map  --problemName warehouseTest --taskFile ./tasks.tasks  --team_sizes 100 200 300 --benchmark_folder ./test
```

1.  /warehouse.domain/maps/warehouse_large.map does not exist here

**Comment by GreatenAnoymous** [comment]
fixed the bugs and updated the command line in the documents

**Comment by nobodyczcz** [comment]
The tutorial structure was adjusted based on the structure of the new readme. 
Still have issues:

1. warehouse map generator does not accepting command line arguments
2.  warehouse map generator read path of config yaml relative to executable path (not current working folder)

for 1, I hide the examples and instructions on using cli flags for now, and only using examples with yaml configuration

Other things I noticed about the benchmark generator with random tasks:

1. taskNum is not the total number of tasks(errands), it is tasks per agent
2. For each team size it generate taskNum*teamsize tasks and overwrite the previous generated task file

**Comment by nobodyczcz** [comment]
@shchan13 

Command line support for warehouse map generator:
1. if nothing is in the command line or the yaml, "invalid configuration error, see -h for available options".
2. Given `-h`, print how to use
3. default values for some parameters in the command line
- rename stationName to stationConfig
- stationConfig value: picking, emmitter, file ;  [default: picking]
- mapName -> output
- output value: file; [default: stdout]
- stationNum value: integer, string max; [default: max]
- storageSize: [default: [3,2]]
- emitterW -> stationDistance
- stationDistance: [default: 2]  
- corridorW -> corridorWidth
- corridorWidth: [default: 1]
- pillarW -> pillarWidth
- pillarW: [default: 4]  
- operW -> operWidth
- operW: [default: 5]

**Comment by nobodyczcz** [comment]
@GreatenAnoymous 

Check all the scripts to make sure they have -h to print how to use, and raise "invalid configuration error, see -h for available options" if no sufficient parameters are given.

Check the cli args package used in these scripts, if you can change the behaviour to "no sufficient parameters are given" to only print the error message.

Issues in the benchmark generator:
1. taskNum is not the total number of tasks(errands), it is tasks per agent
2. For each team size it generates taskNum*teamsize tasks and overwrites the previously generated task file

Correct behavior:
1. taskNum specifies the total number of tasks(errands)
2. only generate one task file once on the total number of tasks

**Pull request merged**
